
import { Client, Document, Memo } from './types';

export const clients: Client[] = [
  {
    id: '1',
    name: '株式会社山本製作所',
    industry: '製造業',
    closingMonth: 2,
    manager: '山田',
    yearsEnrolled: 12,
    documentCount: 156,
    pendingDocuments: 3,
    contractStartDate: '2012-04-01',
    lastUpdated: '2024-03-15',
  },
  {
    id: '2',
    name: '有限会社鈴木商店',
    industry: '小売業',
    closingMonth: 3,
    manager: '佐藤',
    yearsEnrolled: 8,
    documentCount: 98,
    pendingDocuments: 0,
    contractStartDate: '2016-10-01',
    lastUpdated: '2024-02-28',
  },
  {
    id: '3',
    name: '医療法人社団健康会',
    industry: '医療',
    closingMonth: 2,
    manager: '山田',
    yearsEnrolled: 15,
    documentCount: 203,
    pendingDocuments: 5,
    contractStartDate: '2009-06-01',
    lastUpdated: '2024-03-10',
  },
  {
    id: '4',
    name: '合同会社テックラボ',
    industry: 'IT通信',
    closingMonth: 12,
    manager: '鈴木',
    yearsEnrolled: 3,
    documentCount: 42,
    pendingDocuments: 1,
    contractStartDate: '2021-01-15',
    lastUpdated: '2024-01-20',
  },
  {
    id: '5',
    name: '株式会社田中建設',
    industry: '建設業',
    closingMonth: 9,
    manager: '佐藤',
    yearsEnrolled: 20,
    documentCount: 312,
    pendingDocuments: 2,
    contractStartDate: '2004-04-01',
    lastUpdated: '2023-12-25',
  },
  {
    id: '6',
    name: '社会福祉法人やすらぎ',
    industry: '福祉',
    closingMonth: 2,
    manager: '鈴木',
    yearsEnrolled: 10,
    documentCount: 178,
    pendingDocuments: 4,
    contractStartDate: '2014-07-01',
    lastUpdated: '2024-03-12',
  },
];

export const getDocuments = (clientId: string): Document[] => [
  { id: 'd1', name: '決算報告書', type: '決算書類', year: 'R5', status: '登録済', updatedAt: '2024-02-15' },
  { id: 'd2', name: '勘定科目内訳書', type: '決算書類', year: 'R5', status: '登録済', updatedAt: '2024-02-15' },
  { id: 'd3', name: '法人概況説明書', type: '決算書類', year: 'R5', status: '登録済', updatedAt: '2024-02-15' },
  { id: 'd4', name: '法人税申告書', type: '申告書', year: 'R5', status: '登録済', updatedAt: '2024-03-01' },
  { id: 'd5', name: '消費税申告書', type: '申告書', year: 'R5', status: '登録済', updatedAt: '2024-03-01' },
  { id: 'd6', name: '地方税申告書', type: '申告書', year: 'R5', status: '登録済', updatedAt: '2024-03-01' },
  { id: 'd7', name: '異動届', type: '届出書', year: 'R5', status: '登録済', updatedAt: '2023-08-15' },
  { id: 'd8', name: '届出書控え', type: '届出書', year: 'R4', status: '登録済', updatedAt: '2022-08-15' },
  { id: 'd9', name: '登記簿謄本', type: '預かり書類', year: 'R6', status: '預かり中', updatedAt: '2024-03-05' },
  { id: 'd10', name: '定款', type: '預かり書類', year: 'R6', status: '登録済', updatedAt: '2012-04-01' },
  { id: 'd11', name: '株主名簿', type: '預かり書類', year: 'R6', status: '預かり中', updatedAt: '2024-01-10' },
];

export const getMemos = (clientId: string): Memo[] => [
  { id: 'm1', date: '2024/03/15', manager: '山田', content: 'R5決算時に減価償却方法の変更を検討。次回面談時にシミュレーションを提示予定。' },
  { id: 'm2', date: '2023/08/15', manager: '佐藤', content: '代表者変更届を提出済。原本は返却し、スキャンデータを登録。' },
  { id: 'm3', date: '2023/06/01', manager: '山田', content: '消費税の届出について相談あり。簡易課税の選択適否を再検討。' },
];
